api:
  key: ${API_KEY:7887}
spring:
  application:
  
      
    name: Slgames
  datasource:
    url: jdbc:mysql://localhost:3306/slgames
    username: root
    password: root
server:
  error:
    include-stacktrace: never
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
